version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      proxy_net:
      inet_net:
    healthcheck:
      test: "/etc/init.d/mysql status"
  web:
    build: .
    working_dir: /var/www/html
    depends_on: [db]
    volumes:
       - ./file-web:/var/www/html/
    networks:
      proxy_net:
      inet_net:
    links:
      - db
    healthcheck:
      test: curl -f http://web:80/ || exit 0
  proxy:
    image: nginx:1.15.6
    depends_on: [web]
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      proxy_net:
    healthcheck:
      test: curl -f http://localhost/ || exit 0
  pma:
    image: docker.io/bitnami/phpmyadmin:5-debian-10
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT_NUMBER: 3306
    volumes:
      - pma-data:/bitnami/mariadb
    networks:
      inet_net:
      proxy_net:
    links:
      - db
    healthcheck:
      test: curl -f http://pma:8080/ || exit 0
volumes:
  db-data:
  pma-data:
networks:
  proxy_net:
  inet_net:
